# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-30 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_encoding', '0002_update_field_definitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='conversion_error',
            field=models.BooleanField(default=False, verbose_name='Conversion error?'),
        ),
        migrations.AddField(
            model_name='format',
            name='conversion_error_msg',
            field=models.CharField(blank=True, default=b'', max_length=10000, verbose_name='Conversion error msg'),
        ),
    ]
