# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-31 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django_ffmpeg.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ffmpeg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertvideo',
            name='other',
            field=models.CharField(blank=True, default=b'', max_length=2000, verbose_name='Other reason'),
        ),
        migrations.AddField(
            model_name='convertvideo',
            name='output_video_mov',
            field=models.FileField(null=True, upload_to=django_ffmpeg.models.video_file_path, verbose_name='MOV Video file'),
        ),
        migrations.AddField(
            model_name='convertvideo',
            name='output_video_mp4',
            field=models.FileField(null=True, upload_to=django_ffmpeg.models.video_file_path, verbose_name='MP4 Video file'),
        ),
        migrations.AddField(
            model_name='convertvideo',
            name='reason',
            field=models.IntegerField(choices=[(1, 'Violence'), (2, 'Nudity'), (3, 'Hate'), (4, 'Other'), (5, 'Conversion error')], default=4, verbose_name='Reject reason'),
        ),
        migrations.AddField(
            model_name='convertvideo',
            name='revision',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Reviewed')], default=1, verbose_name='Revision status'),
        ),
    ]
