# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-01 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ffmpeg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enqueuedvideo',
            name='command',
            field=models.TextField(blank=True, help_text=b'Example: /usr/bin/ffmpeg -nostats -y -i %(input_file)s -acodec libmp3lame -ar 44100 -f flv %(output_file)s', null=True, verbose_name='System command to convert video'),
        ),
        migrations.AlterField(
            model_name='enqueuedvideo',
            name='convert_extension',
            field=models.CharField(blank=True, editable=False, help_text='Without dot: `.`', max_length=5, null=True, verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='enqueuedvideo',
            name='convert_status',
            field=models.CharField(blank=True, choices=[(b'pending', 'Pending convert'), (b'started', 'Convert started'), (b'converted', 'Converted'), (b'error', 'Not converted due to error')], default=b'pending', max_length=16, null=True, verbose_name='MP4 Video conversion status'),
        ),
        migrations.AlterField(
            model_name='enqueuedvideo',
            name='thumb_command',
            field=models.TextField(blank=True, help_text=b'Example: /usr/bin/ffmpeg -hide_banner -nostats -i %(in_file)s -y -frames:v 1 -ss %(thumb_frame)s %(out_file)s', null=True, verbose_name='System command to convert thumb'),
        ),
        migrations.AlterField(
            model_name='enqueuedvideo',
            name='thumb_frame',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Frame number for thumbnail'),
        ),
    ]
