# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-01 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django_ffmpeg.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ffmpeg', '0002_auto_20190401_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertvideo',
            name='video',
            field=models.FileField(upload_to=django_ffmpeg.models.upload_reformat_name, verbose_name='Video file'),
        ),
        migrations.AlterField(
            model_name='enqueuedvideo',
            name='convert_status',
            field=models.CharField(blank=True, choices=[(b'pending', 'Pending convert'), (b'started', 'Convert started'), (b'converted', 'Converted'), (b'error', 'Not converted due to error')], default=b'pending', max_length=16, null=True, verbose_name='Video conversion status'),
        ),
        migrations.AlterField(
            model_name='enqueuedvideo',
            name='converted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Convert time'),
        ),
        migrations.AlterField(
            model_name='enqueuedvideo',
            name='converted_video',
            field=models.FileField(null=True, upload_to=django_ffmpeg.models.video_file_path, verbose_name='Converted Video file'),
        ),
        migrations.AlterField(
            model_name='enqueuedvideo',
            name='last_convert_msg',
            field=models.TextField(blank=True, null=True, verbose_name='Message from last converting command'),
        ),
    ]
