# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-01 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ffmpeg', '0002_auto_20190331_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convertvideo',
            options={'verbose_name': 'Review Video', 'verbose_name_plural': 'Review Videos'},
        ),
        migrations.AddField(
            model_name='convertvideo',
            name='convert_status_mov',
            field=models.CharField(choices=[(b'pending', 'Pending convert'), (b'started', 'Convert started'), (b'converted', 'Converted'), (b'error', 'Not converted due to error')], default=b'pending', max_length=16, verbose_name='MOV Video conversion status'),
        ),
        migrations.AddField(
            model_name='convertvideo',
            name='converted_mov_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Convert time MOV'),
        ),
        migrations.AddField(
            model_name='convertvideo',
            name='last_convert_msg_mov',
            field=models.TextField(blank=True, null=True, verbose_name='Message from last converting command'),
        ),
        migrations.AlterField(
            model_name='convertvideo',
            name='convert_status',
            field=models.CharField(choices=[(b'pending', 'Pending convert'), (b'started', 'Convert started'), (b'converted', 'Converted'), (b'error', 'Not converted due to error')], default=b'pending', max_length=16, verbose_name='MP4 Video conversion status'),
        ),
        migrations.AlterField(
            model_name='convertvideo',
            name='converted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Convert time MP4'),
        ),
        migrations.AlterField(
            model_name='convertvideo',
            name='last_convert_msg',
            field=models.TextField(blank=True, null=True, verbose_name='Message from last converting command'),
        ),
    ]
