# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cffmpeg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enqueuedvideo',
            name='full_convert_msg',
            field=models.TextField(blank=True, null=True, verbose_name='Full Message from last converting command'),
        ),
    ]
