# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cffmpeg', '0003_auto_20190405_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertvideo',
            name='status',
            field=models.IntegerField(choices=[(b'pending', b'Pending'), (b'approved', b'Approved'), (b'rejected', b'Rejected')], default=b'pending', verbose_name='Acceptance status'),
        ),
    ]
