# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cffmpeg', '0004_auto_20190405_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertvideo',
            name='reason',
            field=models.CharField(choices=[(b'violence', 'Violence'), (b'nudity', 'Nudity'), (b'hate', 'Hate'), (b'other', 'Other'), (b'conversion_error', 'Conversion error')], default=b'other', help_text='If select other, please fill the field below.', max_length=16, verbose_name='Reject reason'),
        ),
        migrations.AlterField(
            model_name='convertvideo',
            name='revision',
            field=models.CharField(choices=[(b'pending', 'Pending'), (b'reviewed', 'Reviewed')], default=b'pending', help_text='Set as reviewed if you are ok with everything in this page.', max_length=16, verbose_name='Revision status'),
        ),
        migrations.AlterField(
            model_name='convertvideo',
            name='status',
            field=models.CharField(choices=[(b'pending', b'Pending'), (b'approved', b'Approved'), (b'rejected', b'Rejected')], default=b'pending', help_text='Select the status of this review.', max_length=16, verbose_name='Acceptance status'),
        ),
    ]
