# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-02 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(editable=False, null=True)),
                ('height', models.PositiveIntegerField(editable=False, null=True)),
                ('duration', models.FloatField(editable=False, null=True)),
                ('video_available', models.BooleanField(default=False, verbose_name='Video available')),
                ('video_mp4', models.FileField(blank=True, default=b'', upload_to=b'')),
                ('video_mov', models.FileField(blank=True, default=b'', upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Video_revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('revision', models.IntegerField(choices=[(1, b'Pending'), (2, b'Reviewed')], default=1, verbose_name='Revision status')),
                ('status', models.IntegerField(choices=[(1, b'Pending'), (2, b'Approved'), (3, b'Rejected'), (4, b'Error')], default=1, verbose_name='Status')),
                ('reason', models.IntegerField(choices=[(1, b'Violence'), (2, b'Nudity'), (3, b'Hate'), (4, b'Other'), (5, b'Conversion error')], default=1, verbose_name='Reject reason')),
                ('other', models.CharField(blank=True, default=b'', max_length=2000, verbose_name='Other reason')),
                ('visible', models.BooleanField(default=False, verbose_name='Is visible?')),
                ('conversion_error_msg', models.CharField(blank=True, default=b'', max_length=10000, verbose_name='Conversion error msg')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_rev', to='media_library.Video')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'verbose_name': 'Video review',
                'verbose_name_plural': 'Videos review',
            },
        ),
    ]
