# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-27 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_auto_20160704_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('revision', models.IntegerField(choices=[(1, b'Pending'), (2, b'Reviewed')], default=1, verbose_name='Revision date')),
                ('status', models.IntegerField(choices=[(1, b'Pending'), (2, b'Approved'), (3, b'Rejected')], default=1, verbose_name='Status')),
                ('reason', models.IntegerField(choices=[(1, b'Violence'), (2, b'Nudity'), (3, b'Hate'), (4, b'Other')], default=1, verbose_name='Reject reason')),
                ('other', models.CharField(blank=True, default=b'', max_length=2000, verbose_name='Other reason')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'verbose_name': 'Video review',
                'verbose_name_plural': 'Videos review',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='video_available',
            field=models.BooleanField(default=False, verbose_name='Video available'),
        ),
        migrations.AddField(
            model_name='video_revision',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_rev', to='media_library.Video'),
        ),
    ]
