# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-30 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0004_auto_20190330_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_revision',
            name='conversion_error_msg',
            field=models.CharField(blank=True, default=b'', max_length=10000, verbose_name='Conversion error msg'),
        ),
    ]
